import Head from 'next/head'
import Image from 'next/image'
import Templates from '../components/templates'
import styles from '../styles/Home.module.css'
import image from 'next/image';


export default function Home() {
  return (
    <>
      <Head>
        <title>Crud data</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Templates content={
        <>
          <div className="card">
            {/* <img className="card-img-top" src="img_avatar1.png" alt="Card image" /> */}
            <div className="card-body">
              <h4 className="card-title">John Doe</h4>
              <p className="card-text">Some example text some example text. John Doe is an architect and engineer</p>
              <a href="#" className="btn btn-primary">See Profile</a>
            </div>
          </div>
        </>

      }></Templates>

    </>
  )
}
