import Head from 'next/head'
import { useEffect, useState } from 'react';
import Router from "next/router";
import axios from 'axios';

export default function Login() {

    const [value, setValue] = useState({
        username: '',
        password: '',
    });

    const [namaapp, SetNamaApp] = useState({
        namaapp: ''
    });
    const handleChange = (e) => {
        setValue({
            ...value,
            [e.target.name]: e.target.value
        })
    }

    const handleSubmit = () => {
        event.preventDefault();

        const session = {
            username: value.username,
            password: value.password
        }

        const test = localStorage.setItem('session', session);
        console.log(value);
        // Router.push('/');
    }
    useEffect(() => {
        axios.get('/data_indeiti').then((e) => {
            const b = JSON.parse(e.data);
            setName({
                identitas: e.nama_app
            });
        });

    }, []);



    return (<div className="login-page">


        <Head>
            <title>Login Aplikasi</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://adminlte.io/themes/v3/plugins/fontawesome-free/css/all.min.css" />
            <link rel="stylesheet" href="https://adminlte.io/themes/v3/plugins/fontawesome-free/css/all.min.css" />

        </Head>
        <div className="login-box">
            <div className="login-logo">
                <a href="../../index2.html">
                    <b>Admin</b>LTE
                </a>
            </div>
            <div className="card">
                <div className="card-body login-card-body">
                    <p className="login-box-msg">Sign in to start your session</p>
                    <form action="" method="post" onSubmit={handleSubmit}>
                        <div className="input-group mb-3">
                            <input type="username" name='username' onChange={handleChange} className="form-control" placeholder="Email" value={value.username} />
                            <div className="input-group-append">
                                <div className="input-group-text">
                                    <span className="fas fa-envelope" />
                                </div>
                            </div>
                        </div>
                        <div className="input-group mb-3">
                            <input
                                type="password"
                                name='password'
                                className="form-control"
                                placeholder="Password"
                                onChange={handleChange}
                                value={value.password}
                            />
                            <div className="input-group-append">
                                <div className="input-group-text">
                                    <span className="fas fa-lock" />
                                </div>
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-8">
                                <div className="icheck-primary">
                                    <input type="checkbox" id="remember" />
                                    <label htmlFor="remember">Remember Me</label>
                                </div>
                            </div>
                            <div className="col-4">
                                <button type="submit" className="btn btn-primary btn-block">
                                    Sign In
                                </button>
                            </div>
                        </div>
                    </form>
                    <div className="social-auth-links text-center mb-3">
                        <p>- OR -</p>
                        <a href="#" className="btn btn-block btn-primary">
                            <i className="fab fa-facebook mr-2" /> Sign in using Facebook
                        </a>
                        <a href="#" className="btn btn-block btn-danger">
                            <i className="fab fa-google-plus mr-2" /> Sign in using Google+
                        </a>
                    </div>
                    <p className="mb-1">
                        <a href="forgot-password.html">I forgot my password</a>
                    </p>
                    <p className="mb-0">
                        <a href="register.html" className="text-center">
                            Register a new membership
                        </a>
                    </p>
                </div>
            </div>
        </div>



    </div>);

}

